### ISSUE TITLE
Feature request - Download to specific directory

### ISSUE THREAD

**Issue by dskvr** [dsaltares/fetch-gh-release-asset#11]
By default, this action downloads to the CWD, but it would be super handy if it could be downloaded to a user-defined directory. Presently requires that an extra step is added to accomplish this.

**Comment by dsaltares** [comment]
Thanks a lot for the request! Would you be able to send a PR implementing this feature? I would gladly review. I agree that this could be useful to folks.

**Comment by dsaltares** [comment]
Should be solved by #15.
