### ISSUE TITLE
Multiple Files to download at once

### ISSUE THREAD

**Issue by spalaniappan-pg** [dsaltares/fetch-gh-release-asset#25]
Hi I would like to check if its possible to download multiple files from Github release. We have binaries and source code stored in separate zip files from releases which we would like to download at same time. I can use it perfectly for 1 file with the exact file name, but for more than one its not working. Kindly let me know on how to use it for multiple files. I tried with commas and also with Quotes. but nothing worked. As attached in the picture, i have multiple files which needs to be downloaded.
![releaseasset](https://user-images.githubusercontent.com/61496082/128679056-155352f5-14ba-4931-a8fb-21db8bdec334.png)

**Comment by dsaltares** [comment]
Currently, this action does not support multiple file download in one step.

The way to go here would be to have 3 separate steps in your workflow, all three leveraging this action, one per file you want to download.

Would this not work for you?

**Comment by spalaniappan-pg** [comment]
Hi, thanks for your prompt response. 
Yes for the timebeing, i'm trying to implement something similar to collect all data in seperate steps.

**Comment by spalaniappan-pg** [comment]
@dsaltares : Just wanted to check one more information, is it possible to download the source code (which is the second folder in the image above) that is archived usually from the GitHub release using this actions?

**Comment by dsaltares** [comment]
From https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8#gistcomment-2602381 looks like the source code packages will not appear as downloadable artefacts from the API.

**Comment by dsaltares** [comment]
I believe you can now do this via the `regex` and `file` options. See usage samples here https://github.com/dsaltares/fetch-gh-release-asset#example-usage.
