### ISSUE TITLE
Change asset missing from error into warning

### ISSUE THREAD

**Issue by ffMathy** [dsaltares/fetch-gh-release-asset#26]
Right now, if the asset is missing, an error is thrown:

> [!] Release asset not found
> Release data: {
>   "message": "Not Found",
>   "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-release-by-tag-name"
> }

I am in a situation where the asset isn't always there, so I'd like an option to suppress that error, or perhaps we could just always turn it into a warning?

If people's pipelines rely on the asset being there, then their pipelines would fail anyway later in the process.

**Comment by dsaltares** [comment]
Closing, I think it'd be much better if this was supported at the github action level. See https://github.com/dsaltares/fetch-gh-release-asset/pull/27#issuecomment-975490613.
