### ISSUE TITLE
Support wildcard in `file`

### ISSUE THREAD

**Issue by fzzr-** [dsaltares/fetch-gh-release-asset#33]
Please add support regex or just `*` for `file` field.
It needed for case where filename contains some various changing info. Version, [for example](https://github.com/mozilla/grcov/releases/tag/v0.8.6). In case of you need "latest" version/release you can't know the filename.

**Comment by dsaltares** [comment]
That sounds like a good idea, thanks for opening an issue. Would you be able to submit a PR? I'd gladly accept it.

**Comment by bjaanes** [comment]
@dsaltares What is the status on that PR? I'm currently blocked on this and would love a new release with this feature included :)

**Comment by dsaltares** [comment]
You're welcome, you can now use 0.0.8 too https://github.com/dsaltares/fetch-gh-release-asset/releases/tag/0.0.8

**Comment by dsaltares** [comment]
Closing this one for now, please ping me if there are any issues with the feature.
