### ISSUE TITLE
Add support for GitHub enterprise

### ISSUE THREAD

**Issue by lcmgh** [dsaltares/fetch-gh-release-asset#37]
There is no option to use the current GitHub server as always github.com is being used.

**Comment by dsaltares** [comment]
Thanks for the issue @lcmgh, would love to see a PR for this, it sounds like a great addition. I had no idea Github Enterprise folks would be interested in this action.

**Comment by dsaltares** [comment]
Looks like `octokit` lets you pass a `baseUrl` to hit your GH enterprise instance: https://github.com/octokit/octokit.js/#constructor-options.

Will take a look.

**Comment by dsaltares** [comment]
@lcmgh  https://github.com/dsaltares/fetch-gh-release-asset/pull/46 should solve it.
