### ISSUE TITLE
Incorrect version tag

### ISSUE THREAD

**Issue by Jikoo** [dsaltares/fetch-gh-release-asset#41]
v0.0.6 appears to have incorrectly been tagged as v0.06. This causes Dependabot to be unable to properly update the action. For example, see https://github.com/Jikoo/OpenInv/pull/78 - v0.0.8 is visible in the changelog, but due to the tagging error v0.0.6 is considered to be the highest version available.

![image](https://user-images.githubusercontent.com/1353270/166483184-0d106b27-03b3-4780-b63f-626ca82f4b1e.png)

**Comment by dsaltares** [comment]
Thanks for reporting, that was my bad obviously 🤦.
Instead of deleting an already published tag, I have decided to release version 1.0.0 and adopt semver from now on.
See https://github.com/dsaltares/fetch-gh-release-asset/releases/tag/1.0.0.
