### ISSUE TITLE
consider publishing major release tags

### ISSUE THREAD

**Issue by qrkourier** [dsaltares/fetch-gh-release-asset#57]
It's a convenient convention for GH Actions to publish a major release tag like `v1` that provides reverse-compatible improvements to subscribers. Will you consider tagging your latest compatible releases with `v1` to provide an alternative to subscribing to `master` and pinned releases?

**Comment by dsaltares** [comment]
Yes, we already have 1.1.0 as the latest published version.

There are newer changes that are not included. So in some issues I may have suggested pinning to master for the time being.

I'll release a new version with the current master soon.

**Comment by qrkourier** [comment]
Thank you for this Action. My hope is for a major release tag like `v1`. By subscribing to the major release tag in my workflows I can expect reverse-compatible changes to become available automatically. No need for me to re-pin the latest patch release, e.g. `v1.1.1`. This is the convention for many GH Actions.

**Comment by dsaltares** [comment]
https://github.com/dsaltares/fetch-gh-release-asset/releases/tag/1.1.1 Is released and is tagged with `latest` as well.
