### ISSUE TITLE
Update to NodeJS 20 runtime

### ISSUE THREAD

**Issue by ankon** [dsaltares/fetch-gh-release-asset#61]
We're receiving warnings when using this action about moving to NodeJS 20, pointing to https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

https://github.com/dsaltares/fetch-gh-release-asset/blob/cdaf216b2a5baa0f20eecbf460912cc9947f2577/action.yaml#L32

**Comment by lukasz-mitka** [comment]
@dsaltares Could you handle that?

**Comment by mkroening** [comment]
Note that you can also use GitHub CLI, which is preinstalled on GitHub's runners, to download release assets: [`gh release download`](https://cli.github.com/manual/gh_release_download)

**Comment by johnfilo-kmart** [comment]
I would love for this to be bumped to node20 also, thanks!

**Comment by peternorthphorest** [comment]
Hello! Will this be updated to NodeJs 20 any time soon?

**Comment by peternorthphorest** [comment]
Hi, is there a plan to update this to use NodeJs 20?

**Comment by dsaltares** [comment]
New release available too https://github.com/dsaltares/fetch-gh-release-asset/releases/tag/1.1.2.
